---
- hosts: 10.11.93.8 
  remote_user: admin
  become: true

  vars: 
    doc_root: /etc/sonic

  tasks:  
    
    - name: Create custom document root
      file: path={{ doc_root }}

    - name: copy the config from Server to 10.11.93.8
      copy: src=config_db.json dest={{ doc_root }}/config_db.json   
      

   
    - name: config reload
      command: config reload -y  
