---
- hosts: 10.11.93.8 
  remote_user: admin
  become: true

  vars: 
    doc_root: /etc/sonic

  tasks:  
    
    - name: Create custom document root
      file: path={{ doc_root }}

    - name: copy the config from Server to 10.11.93.8
      copy: src=config_db.json dest={{ doc_root }}/config_db.json   
     

   
    - name: config reload
      command: config reload -y 
 
    - name:  "Check is System Is ready"
      command: "show system status"
      register: show_system
      until: show_system.stdout.find("System is ready") != -1
      retries: 5
      delay: 10
  

    - debug: var=show_system.stdout_lines

    - name: Get names of all dockers running
      shell: docker ps | grep docker
      register: output

    - debug: var=output.stdout_lines

    - name: verify number of docker process running , it should be 19 as of MR3.0.1
      assert: { that: "{{ output.stdout_lines | length }} == 19"}   
