---
# this is an example of how to run repeated task elements over lists
# of items, for example, installing multiple packages or configuring
# multiple users

- hosts: all
  remote_user: admin
  become: true
 
  tasks:

  - name: install packages
    apt: name={{ item }} state=present
    with_items:
       - apache2 
       - vim
         #  - name: configure users
         #user: name={{ item }} state=present groups=wheel
         #with_items:
         #- testuser1
         #- testuser2

         #- name: remove users
         #user: name={{ item }} state=absent
         #with_items:
         #- testuser1
         #- testuser2

  - name: copy templates
    template: src={{ item.src }} dest={{ item.dest }}
    with_items:
        - src: templates/testsource1
          dest: /usr/share/test1.conf
        - src: templates/testsource2
          dest: /usr/share/test2.conf

  - name: check for file          
    command: 'ls -l /usr/share | grep test'
    register: ls_command
    success_when: test  in ls_command.stderr
    

    #  - debug: var=ls_command
